"English":
- changed-files:
  - any-glob-to-any-file: 'src/en/**'

"Russian":
- changed-files:
  - any-glob-to-any-file: 'src/ru/**'

"Ukrainian":
- changed-files:
  - any-glob-to-any-file: 'src/ua/**'

"Scripts":
- changed-files:
  - any-glob-to-any-file: 'scripts/**'

"Design":
- changed-files:
  - any-glob-to-any-file: 
    - 'src/en/general-proposals/**'
    - 'src/en/**/proposals/**'
